#!/bin/bash
	sudo apt update
	sudo apt upgrade
	sudo apt install apache2

	sudo ufw app list

	sudo ufw app info "Apache Full"

	sudo ufw allow in "Apache Full"

	sudo apt install mysql-server
	sudo mysql_secure_installation
	sudo mysql
	
	SELECT user,authentication_string,plugin,host FROM mysql.user;
	
	ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';    // please note here replace the "password" with yours.
	
	FLUSH PRIVILEGES;
	
	SELECT user,authentication_string,plugin,host FROM mysql.user;
	exit

	sudo apt install php libapache2-mod-php php-mysql

	sudo systemctl restart apache2
	sudo systemctl status apache2
	
	sudo apt install php7.2-common php7.2-mysql php7.2-xml php7.2-xmlrpc php7.2-curl php7.2-gd php7.2-imagick php7.2-cli php7.2-dev php7.2-imap php7.2-mbstring php7.2-opcache php7.2-soap php7.2-zip php7.2-intl -y
	
	sudo systemctl restart apache2

  	sudo apt update
 	sudo apt install phpmyadmin php-mbstring php-gettext

	sudo phpenmod mbstring
 	sudo systemctl restart apache2

	sudo chown -R ubuntu:root /var/www/html
	sudo find html -type d -exec chmod 775 {} \;
	sudo find html -type f -exec chmod 664 {} \;

	sudo a2enmod rewrite
	sudo service apache2 restart
